-- Grant schema
Grant CONNECT, RESOURCE, DBA TO SCBOARD

-- Create Sequence
CREATE SEQUENCE SEQ_ARTICLE
INCREMENT BY 1
START WITH 1
MAXVALUE  999999999
MINVALUE 1
NOCYCLE
CACHE 20;

--------------------------------------------------

CREATE SEQUENCE SEQ_MEMBER
INCREMENT BY 1
START WITH 1
MAXVALUE  999999999
MINVALUE 1
NOCYCLE
CACHE 20;

-- SCBOARD."MEMBER" definition

CREATE TABLE "SCBOARD"."MEMBER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LOGINID" VARCHAR2(20) NOT NULL ENABLE, 
	"LOGINPW" VARCHAR2(100) NOT NULL ENABLE, 
	"AUTH" VARCHAR2(1), 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(20), 
	"CELLPHONENO" VARCHAR2(20), 
	"EMAIL" VARCHAR2(50), 
	"DELSTATUS" VARCHAR2(1) DEFAULT '0', 
	"REGDATE" DATE, 
	"MODDATE" DATE, 
	"DELDATE" DATE, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "SCBOARD"."PK_MEMBER" ON "SCBOARD"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE SCBOARD."MEMBER" IS '회원 테이블';
COMMENT ON COLUMN SCBOARD."MEMBER".ID IS 'ID';
COMMENT ON COLUMN SCBOARD."MEMBER".LOGINID IS '회원ID';
COMMENT ON COLUMN SCBOARD."MEMBER".LOGINPW IS '회원 패스워드';
COMMENT ON COLUMN SCBOARD."MEMBER".AUTH IS '권한레벨(3:일반, 7:관리자)';
COMMENT ON COLUMN SCBOARD."MEMBER".NAME IS '회원명';
COMMENT ON COLUMN SCBOARD."MEMBER".NICKNAME IS '회원 별칭';
COMMENT ON COLUMN SCBOARD."MEMBER".CELLPHONENO IS '연락처';
COMMENT ON COLUMN SCBOARD."MEMBER".EMAIL IS 'EMAIL';
COMMENT ON COLUMN SCBOARD."MEMBER".DELSTATUS IS '탈퇴여부(0:탈퇴전, 1:탈퇴)';
COMMENT ON COLUMN SCBOARD."MEMBER".REGDATE IS '등록일';
COMMENT ON COLUMN SCBOARD."MEMBER".MODDATE IS '정보수정일';
COMMENT ON COLUMN SCBOARD."MEMBER".DELDATE IS '탈퇴일';